#!/bin/sh
set -e

# Ensure shader files have correct permissions
chmod 644 /usr/share/swayfx/shaders/*

# Update manual pages
if [ -x /usr/bin/mandb ]; then
    mandb -q
fi

# Update desktop database
if [ -x /usr/bin/update-desktop-database ]; then
    update-desktop-database -q
fi
