#!/bin/sh
set -e

# Remove shader files
rm -rf /usr/share/swayfx/shaders

# Update manual pages
if [ -x /usr/bin/mandb ]; then
    mandb -q
fi

# Update desktop database
if [ -x /usr/bin/update-desktop-database ]; then
    update-desktop-database -q
fi
